name: hai_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.6
  lottie: ^2.3.2
  audioplayers: ^6.1.0
  google_fonts: ^4.0.3
  just_audio: ^0.9.38
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_musik.png
    - assets/pp.png
    - assets/home_animasi.json
    - assets/music/Seize_The_Day.mp3
    - assets/music/Yung_Kai-Blue.mp3
    - assets/music/Disenchanted.mp3
    - assets/music/Helena.mp3




  
